# Generated by Django 5.2 on 2025-04-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_size', models.CharField(max_length=5)),
                ('product_color', models.CharField(max_length=10)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_catagories', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
