# Generated by Django 5.2 on 2025-04-07 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_main', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
    ]
